name: Run Hardhat Script

on:
  push:
    branches: [ quill-assessment ]
  pull_request:

jobs:
  hardhat:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Compile contracts
        run: npx hardhat compile

      - name: Run Hardhat e2e test script
        run: npx hardhat run scripts/e2e.js --network hardhat
